// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpcRa7vmaCZQ-wqdVGKsI1z7L7_-U7L-Q',
    appId: '1:81277949788:web:9ff256b5ddf84a791bd399',
    messagingSenderId: '81277949788',
    projectId: 'nosefirebase',
    authDomain: 'nosefirebase.firebaseapp.com',
    storageBucket: 'nosefirebase.firebasestorage.app',
    measurementId: 'G-GB7W9EX7MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJcgRhYg-eInRZmJrMffwPBsnnC04LKgQ',
    appId: '1:81277949788:android:6bd49b1502f3cda71bd399',
    messagingSenderId: '81277949788',
    projectId: 'nosefirebase',
    storageBucket: 'nosefirebase.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHIPaYJbJIkftSDo9jJK_SqSCU5XFBoI',
    appId: '1:81277949788:ios:8b2091993e63763c1bd399',
    messagingSenderId: '81277949788',
    projectId: 'nosefirebase',
    storageBucket: 'nosefirebase.firebasestorage.app',
    iosBundleId: 'com.example.nosefirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpcRa7vmaCZQ-wqdVGKsI1z7L7_-U7L-Q',
    appId: '1:81277949788:web:40f8d3af9d8724ff1bd399',
    messagingSenderId: '81277949788',
    projectId: 'nosefirebase',
    authDomain: 'nosefirebase.firebaseapp.com',
    storageBucket: 'nosefirebase.firebasestorage.app',
    measurementId: 'G-SVQB20J96Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHIPaYJbJIkftSDo9jJK_SqSCU5XFBoI',
    appId: '1:81277949788:ios:8b2091993e63763c1bd399',
    messagingSenderId: '81277949788',
    projectId: 'nosefirebase',
    storageBucket: 'nosefirebase.firebasestorage.app',
    iosBundleId: 'com.example.nosefirebase',
  );

}